### ISSUE TITLE
cypressServerCommand: won't let testRunner know something went wrong

### ISSUE THREAD

**Issue by JoeSchr** [graphile/starter#124]
It seems to me, that this error handling code is never reached
```js
 } catch (e) {
      /*
       * If anything goes wrong, let the test runner know so that it can fail
       * the test.
       */
      res.status(500).json({
        error: {
          message: e.message,
          stack: e.stack,
        },
      });
```
https://github.com/graphile/starter/blob/ad69a9c25c86fe86896ca9fb4d8c4fd450ef1521/%40app/server/src/middleware/installCypressServerCommand.ts#L75

because it get's handled by `/work/@app/server/src/middleware/installErrorHandler.ts` before that. 

Did I just mess up my configuration or can somebody confirm that?

On my end this is bad for cypress testrunner because it just waits forever until a timeout without any information (there is a error log in the server cli printed by `installErrorHandler.ts` ofc)

**Comment by benjie** [comment]
I don’t think that’s right. Do you know what went wrong/where the error originated? You could try putting a throw in the try block to see what happens, I’m pretty sure it should work fine.

**Comment by JoeSchr** [comment]
yeah, the error originated from `runCommand` here: 
https://github.com/graphile/starter/blob/ad69a9c25c86fe86896ca9fb4d8c4fd450ef1521/%40app/server/src/middleware/installCypressServerCommand.ts#L56

I'm writing a test for a failed login, so I wanted to get a 401/500 response.

This is my modified version of yours (without creating a testuser before login):
```js
  } else if (command === "login") {
    const {
      username = "testuser",
      password = "TestUserPassword",
      next = "/",
    } = payload;
    login(username, password, rootPgPool, req, res, next);
    return null;
```
definition for above `login` function

```js
async function login(
  username: string,
  password: string,
  rootPgPool: Pool,
  req: Request,
  res: Response,
  next: string
) {
  // Call our login function to find out if the username/password combination exists
  const {
    rows: [session],
  } = await rootPgPool.query(
    `select sessions.* from app_private.login($1, $2) sessions where not (sessions is null)`,
    [username, password]
  );

  if (!session) {
    const error = new Error("Incorrect username/password");
    error["code"] = "CREDS";
    // replaces `throw error` here:
    // because installErrorHandler.ts catches it
    res.status(401).json({
      error: {
        message: error.message,
        stack: error.stack,
        code: "CREDS",
      },
    });
  }

  if (session.uuid) {
    // Tell Passport.js we're logged in
    await req.login({ session_id: session.uuid }, () => {
      res.redirect(next || "/");
    });
  }
  // failed
  const error = new Error("Login failed");
  res.status(500).json({
    error: {
      message: error.message,
      stack: error.stack,
    },
  });
}
```

**Comment by benjie** [comment]
I added `throw new Error("TESTING")` to line 144 (inside the `} else if (command === "login") {` block) and then triggered the server:

```
$ curl http://localhost:5678/cypressServerCommand?command=login
{"error":{"message":"TESTING","stack":"Error: TESTING\n    at runCommand (/home/benjie/Dev/starter/@app/server/src/middleware/installCypressServerCommand.ts:144:11)\n    at handleCypressServerCommand (/home/benjie/Dev/starter/@app/server/src/middleware/installCypressServerCommand.ts:56:28)\n    at Layer.handle [as handle_request] (/home/benjie/Dev/starter/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/benjie/Dev/starter/node_modules/express/lib/router/route.js:137:13)\n    at urlencodedParser (/home/benjie/Dev/starter/node_modules/body-parser/lib/types/urlencoded.js:91:7)\n    at Layer.handle [as handle_request] (/home/benjie/Dev/starter/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/benjie/Dev/starter/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/benjie/Dev/starter/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/benjie/Dev/starter/node_modules/express/lib/router/layer.js:95:5)\n    at /home/benjie/Dev/starter/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/home/benjie/Dev/starter/node_modules/express/lib/router/index.js:335:12)\n    at next (/home/benjie/Dev/starter/node_modules/express/lib/router/index.js:275:10)\n    at SendStream.error (/home/benjie/Dev/starter/node_modules/serve-static/index.js:121:7)\n    at SendStream.emit (events.js:210:5)\n    at SendStream.error (/home/benjie/Dev/starter/node_modules/send/index.js:270:17)\n    at SendStream.onStatError (/home/benjie/Dev/starter/node_modules/send/index.js:421:12)"}}
```

This result is what I would expect. Please can you reproduce the issue with Graphile Starter verbatim and let me know reproduction steps?

**Comment by JoeSchr** [comment]
Copy that. you can close it meanwhile if you want


__

Typed on a mobile, please excuse any typing mistakes or short-spokeness.

**Comment by benjie** [comment]
Okay; feel free to reopen if you can reproduce :+1:

**Comment by JoeSchr** [comment]
So I finally got to the bottom of this, point is, I got my async/await mixed up and forgot and `return await callXY()` 🤦 

Sorry for the noise
