### ISSUE TITLE
local run windows: password authentification failed 

### ISSUE THREAD

**Issue by Macfly** [graphile/starter#139]
trying to setup locally with Windows10 and WSL but I have this error (coval is my windows user):

`✘ coval@coco-desk  ~/winhome/Documents/projects/plants/starter-2.2.0   master  yarn setup
yarn run v1.21.1
$ yarn && node ./scripts/setup.js
[1/4] Resolving packages...
success Already up-to-date.
? What would you like to call your database? graphile_starter
? What's the hostname of your database server (include :port if it's not the default :5432)? localhost:6543
? Please enter a superuser connection string to the database server (so we can drop/create the 'graphile_starter' and 'graphile_starter_shadow' databases) - IMPORTANT: it must not be a connection to the 'graphile_starter' database itself, instead try 'template1'. postgres://localhost:6543/template1
? We're going to drop (if necessary):

  - database graphile_starter
  - database graphile_starter_shadow
  - database role graphile_starter_visitor (cascade)
  - database role graphile_starter_authenticator (cascade)
  - database role graphile_starter Yes
Installing or reinstalling the roles and database...
error: password authentication failed for user "coval"
    at Connection.parseE (/c/Users/Coco/Documents/projects/plants/starter-2.2.0/node_modules/pg/lib/connection.js:604:13)
    at Connection.parseMessage (/c/Users/Coco/Documents/projects/plants/starter-2.2.0/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/c/Users/Coco/Documents/projects/plants/starter-2.2.0/node_modules/pg/lib/connection.js:123:22)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
  name: 'error',
  length: 101,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '337',
  routine: 'auth_failed'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

I am not sure where to input my password. I have also creating a user coval in the database but still the same error.
I think it is a stupid mistake but can't find solution.

**Comment by benjie** [comment]
```
? Please enter a superuser connection string to the database server (so we can drop/create the 'graphile_starter' and 'graphile_starter_shadow' databases) - IMPORTANT: it must not be a connection to the 'graphile_starter' database itself, instead try 'template1'. postgres://localhost:6543/template1
```

^ This connection string needs your password in it; something like `postgres://postgresuser:postgrespass@localhost:6543/template1`

**Comment by benjie** [comment]
[semi-automated message] Thanks for your question; hopefully we're well on the way to helping you solve your issue. This doesn't currently seem to be a bug in the library so I'm going to close the issue, but please feel free to keep requesting help below and if it does turn out to be a bug we can definitely re-open it 👍

You can also ask for help in the #help-and-support channel in [our Discord chat](http://discord.gg/graphile).

**Comment by peterdresslar** [comment]
I know that this is a trivially easy question, but for those that are running into it due to a lack of time or interest in the postgresql details: _If_ you have built a db instance in Docker using the laziest command possible...

`docker run --name my-postgres-db -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres`

..._then_ your connection string is

`postgres://postgres:postgres@localhost:5432/postgres`

Note that the docker container does not affect the string.

**Comment by benjie** [comment]
Correct, specifically because `-p 5432:5432` makes the Docker daemon expose the container's 5432 port on localhost. Beware on Mac, sometimes if you use `postgres://localhost/foo` it tries to connect via the unix socket rather than the TCP socket, so you may need to use `postgres://127.0.0.1:5432/foo`. I'm not sure what configuration causes this.
